language: bash
before_script:
    - export dir_root=`pwd`
#before_script:
#     - export dir_root="$PWD"
#    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script:
    - bash -c .test.sh

