#!/bin/bash 
set -o nounset

path=`dirname $0`
pushd "$path">/dev/null
source $path/setup.cfg
#echo "$@" >> $log_wrapper.txt
################################## start

#num="${1:-1}"
#notify-send "croning choose:" " $num"
#sleep "$num"
#########################################
steps(){
print_func



################am I root?
set_user

################set global vars / list.txt can use it

exports


################ load cron's env dump

set_env

################ show error generated by the cron service
show_last_error

################ save the cli call
update_logger

################ 
reset_log
wrap_runner

}
choose=$1
steps

popd
cat -n list.txt
