#!/bin/bash 
set -o nounset

path=`dirname $0`
pushd "$path">/dev/null
source $path/setup.cfg
#echo "$@" >> $log_wrapper.txt
################################## start

#num="${1:-1}"
#notify-send "croning choose:" " $num"
#sleep "$num"
#########################################
steps(){
proxy print_func



################am I root?
proxy set_user

################set global vars / list.txt can use it

proxy exports


################ load cron's env dump

proxy set_env

################ show error generated by the cron service
proxy show_last_error

################ save the cli call
proxy update_logger

################ 
proxy reset_log
proxy wrap_runner

}
choose=${1:-1}
proxy steps

popd
#cat -n list.txt
